% IDENTIFICATION =======================================================
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{paper-enhanced}[
    2021/02/5 Improvement of the paper documentclass
]

% Preliminary declarations =============================================

% Options ==============================================================
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{article}}
\ProcessOptions


% Layout ===============================================================


